# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from my_asr_proto import asr_pb2 as my__asr__proto_dot_asr__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in my_asr_proto/asr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ASRServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transcribe = channel.unary_unary(
                '/asr.ASRService/Transcribe',
                request_serializer=my__asr__proto_dot_asr__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=my__asr__proto_dot_asr__pb2.TranscribeResponse.FromString,
                _registered_method=True)
        self.Recognize = channel.unary_unary(
                '/asr.ASRService/Recognize',
                request_serializer=my__asr__proto_dot_asr__pb2.RecognizeRequest.SerializeToString,
                response_deserializer=my__asr__proto_dot_asr__pb2.RecognizeResponse.FromString,
                _registered_method=True)


class ASRServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Transcribe(self, request, context):
        """Метод для распознавания текста из WAV-файла
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recognize(self, request, context):
        """Метод для классификации фразы (например, определение действия)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ASRServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=my__asr__proto_dot_asr__pb2.TranscribeRequest.FromString,
                    response_serializer=my__asr__proto_dot_asr__pb2.TranscribeResponse.SerializeToString,
            ),
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=my__asr__proto_dot_asr__pb2.RecognizeRequest.FromString,
                    response_serializer=my__asr__proto_dot_asr__pb2.RecognizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'asr.ASRService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('asr.ASRService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ASRService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asr.ASRService/Transcribe',
            my__asr__proto_dot_asr__pb2.TranscribeRequest.SerializeToString,
            my__asr__proto_dot_asr__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/asr.ASRService/Recognize',
            my__asr__proto_dot_asr__pb2.RecognizeRequest.SerializeToString,
            my__asr__proto_dot_asr__pb2.RecognizeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
